name: CI

on: [ workflow_dispatch, push, pull_request ]

jobs:
  ci_stable:
    strategy:
      matrix:
        features:
          - "crypto-rust"
          - "crypto-openssl"
        platform:
          - ubuntu-latest
          - ubuntu-24.04-arm

    runs-on:
      - ${{ matrix.platform }}

    steps:
      - name: install required packages
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev

      - name: Fetch head
        uses: actions/checkout@v5

      - name: Install rust stable
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Format check
        run: cargo fmt --check

      - name: Clippy check
        run: cargo clippy --features=${{ matrix.features }} --no-deps --all-targets -- -D warnings

      - name: Install gnome-keyring
        run: sudo apt-get install -y gnome-keyring

      - name: Start gnome-keyring
        # run gnome-keyring with 'foobar' as the password for the login keyring
        # this will create a new login keyring and unlock it
        # the login password doesn't matter, but the keyring must be unlocked for the tests to work
        run: gnome-keyring-daemon --components=secrets --daemonize --unlock <<< 'foobar'

      - name: Build and Test
        run: cargo test --features=${{ matrix.features }} --verbose

      - name: Build examples
        run: cargo build --features=${{ matrix.features }} --examples --verbose

  ci_msrv:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        features:
          - "crypto-rust"
          - "crypto-openssl"

    steps:
      - name: install required packages
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev

      - name: Fetch head
        uses: actions/checkout@v5

      - name: Install rust MSRV
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.88
          components: clippy

      - name: Clippy check
        run: cargo clippy --features=${{ matrix.features }} --no-deps --all-targets -- -D warnings
